services:
  - type: web
    name: ialdazcheck-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false